"""
e2_condition.py — FastAPI route for the E2 AI Condition Report Agent (Gemini).
"""

from fastapi import APIRouter, HTTPException
from pydantic import ValidationError

from models.schemas import ConditionRequest, ConditionResponse
from services.groq_service import generate_condition_report_groq

router = APIRouter(prefix="/evaluate-condition", tags=["E2 — Condition Agent"])


@router.post(
    "",
    response_model=ConditionResponse,
    summary="Grade product condition using Groq AI (Llama 3)",
    description=(
        "Accepts a structured ProductPassport and returns a grading tier, "
        "score, evidence, and professional condition report generated by Llama 3 via Groq."
    ),
)
async def evaluate_condition(request: ConditionRequest) -> ConditionResponse:
    try:
        result = await generate_condition_report_groq(request)
    except ValidationError as exc:
        raise HTTPException(
            status_code=502,
            detail=f"Groq returned an invalid response structure: {exc.errors()}"
        )
    except ValueError as exc:
        raise HTTPException(
            status_code=502,
            detail=f"Failed to parse Groq response: {str(exc)}"
        )
    except Exception as exc:
        raise HTTPException(
            status_code=500,
            detail=f"Internal error calling Groq API: {str(exc)}"
        )

    return result
